server.port=8080
spring.application.name=bet_settlement
spring.docker.compose.lifecycle-management=START_ONLY

# spring cloud
spring.cloud.stream.function.autodetect=false
spring.cloud.function.definition=onEventOutcome;onBetSettlement

# spring cloud kafka
spring.cloud.stream.kafka.binder.autoCreateTopics=true
spring.cloud.stream.kafka.binder.transaction.transaction-id-prefix=tx-
spring.cloud.stream.kafka.binder.transaction.producer.configuration.acks=all

# spring cloud kafka producer
spring.cloud.stream.kafka.binder.transaction.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.cloud.stream.kafka.binder.transaction.producer.configuration.value.serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# spring cloud kafka - ENTRY - event-outcomes - OUT
spring.cloud.stream.bindings.[event-outcomes].destination=event-outcomes
spring.cloud.stream.bindings.[event-outcomes].producer.use-native-encoding=true
spring.cloud.stream.bindings.[event-outcomes].binder=kafka

# spring cloud kafka - CORE - event-outcomes - IN
spring.cloud.stream.bindings.[onEventOutcome-in-0].destination=event-outcomes
spring.cloud.stream.bindings.[onEventOutcome-in-0].group=core
spring.cloud.stream.bindings.[onEventOutcome-in-0].binder=kafka

# spring cloud rocketmq
spring.cloud.stream.rocketmq.binder.name-server=localhost:9876

# spring cloud rocketmq - CORE - bet-settlements - OUT
spring.cloud.stream.bindings.[bet-settlements].destination=bet-settlements
spring.cloud.stream.bindings.[bet-settlements].binder=rocketmq
spring.cloud.stream.bindings.[bet-settlements].content-type=application/json

# spring cloud rocketmq - SETTLEMENT - bet-settlements - IN
spring.cloud.stream.bindings.[onBetSettlement-in-0].destination=bet-settlements
spring.cloud.stream.bindings.[onBetSettlement-in-0].binder=rocketmq
spring.cloud.stream.bindings.[onBetSettlement-in-0].group=settlement
spring.cloud.stream.bindings.[onBetSettlement-in-0].content-type=application/json

# logging
logging.level.root=ERROR
logging.level.com.betting=DEBUG
logging.level.com.betting.spring.RocketMQConfiguration=INFO
logging.level.org.springframework=INFO
